"""add_index_json_for_program

Revision ID: 0dcfea9db417
Revises: 9660bd8f90bc
Create Date: 2025-04-11 12:44:37.174492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dcfea9db417'
down_revision: Union[str, None] = '9660bd8f90bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_program_exams_gin', 'program', ['exams'], unique=False, postgresql_using='gin')
    op.create_index('ix_program_forms_gin', 'program', ['forms'], unique=False, postgresql_using='gin')
    op.create_index('ix_program_scores_gin', 'program', ['scores'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_program_scores_gin', table_name='program', postgresql_using='gin')
    op.drop_index('ix_program_forms_gin', table_name='program', postgresql_using='gin')
    op.drop_index('ix_program_exams_gin', table_name='program', postgresql_using='gin')
    # ### end Alembic commands ###
