"""update_model_universities

Revision ID: 1dd6781e43df
Revises: 2fb1419cda84
Create Date: 2025-04-01 14:43:40.927195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1dd6781e43df'
down_revision: Union[str, None] = '2fb1419cda84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('universities', 'phone_admission',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('universities', 'phone_general',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('universities', 'email_general',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('universities', 'email_admission',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.ARRAY(sa.TEXT()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('universities', 'email_admission',
               existing_type=sa.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('universities', 'email_general',
               existing_type=sa.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('universities', 'phone_general',
               existing_type=sa.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('universities', 'phone_admission',
               existing_type=sa.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    # ### end Alembic commands ###
