"""MIGRATION=update_id_program

Revision ID: 29f393e2fc58
Revises: 703546cd74f0
Create Date: 2025-04-11 17:15:18.792082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29f393e2fc58'
down_revision: Union[str, None] = '703546cd74f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('program_university_id_key', 'program', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('program_university_id_key', 'program', ['university_id'])
    # ### end Alembic commands ###
