"""MIGRATION=add_index

Revision ID: 6b83d5e529f6
Revises: cba9d31f39cb
Create Date: 2025-04-12 00:17:07.146484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b83d5e529f6'
down_revision: Union[str, None] = 'cba9d31f39cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_dormitory_dormitory', 'dormitory', ['dormitory'], unique=False)
    op.create_index('ix_form_education_form2', 'form', ['education_form2'], unique=False)
    op.create_index('ix_form_price', 'form', ['price'], unique=False)
    op.create_index('ix_form_score', 'form', ['score'], unique=False)
    op.create_index('ix_program_direction', 'program', ['direction'], unique=False)
    op.create_index('ix_university_army', 'universities', ['army'], unique=False)
    op.create_index('ix_university_form_long_name', 'universities', ['long_name'], unique=False)
    op.create_index('ix_university_is_goverment', 'universities', ['is_goverment'], unique=False)
    op.create_index('ix_university_short_name', 'universities', ['short_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_university_short_name', table_name='universities')
    op.drop_index('ix_university_is_goverment', table_name='universities')
    op.drop_index('ix_university_form_long_name', table_name='universities')
    op.drop_index('ix_university_army', table_name='universities')
    op.drop_index('ix_program_direction', table_name='program')
    op.drop_index('ix_form_score', table_name='form')
    op.drop_index('ix_form_price', table_name='form')
    op.drop_index('ix_form_education_form2', table_name='form')
    op.drop_index('ix_dormitory_dormitory', table_name='dormitory')
    # ### end Alembic commands ###
