"""initial_migration

Revision ID: c06342c53904
Revises: 
Create Date: 2025-03-27 17:33:36.674763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06342c53904'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('long_name', sa.Text(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('geolocation', sa.String(), nullable=True),
    sa.Column('is_goverment', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.String(length=10), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('website', sa.String(length=50), nullable=True),
    sa.Column('phone_admission', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('phone_general', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('email_general', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('email_admission', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('long_name')
    )
    op.create_table('dormitory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vuz_long_name', sa.Text(), nullable=False),
    sa.Column('dormitory', sa.Boolean(), nullable=False),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['vuz_long_name'], ['universities.long_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dormitory')
    op.drop_table('universities')
    # ### end Alembic commands ###
