"""MIGRATION=add_new_model_form_for_program

Revision ID: cba9d31f39cb
Revises: 29f393e2fc58
Create Date: 2025-04-11 21:24:19.482148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cba9d31f39cb'
down_revision: Union[str, None] = '29f393e2fc58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('education_form2', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('olympic', sa.String(), nullable=True),
    sa.Column('free_places', sa.Integer(), nullable=True),
    sa.Column('average_score', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_program_forms_gin', table_name='program', postgresql_using='gin')
    op.drop_column('program', 'forms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program', sa.Column('forms', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index('ix_program_forms_gin', 'program', ['forms'], unique=False, postgresql_using='gin')
    op.drop_table('form')
    # ### end Alembic commands ###
