"""MIGRATION=update_dormitory

Revision ID: da0bc20fabef
Revises: 6b83d5e529f6
Create Date: 2025-04-12 09:59:28.512641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da0bc20fabef'
down_revision: Union[str, None] = '6b83d5e529f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dormitory_dormitory', table_name='dormitory')
    op.drop_column('dormitory', 'dormitory')
    op.add_column('universities', sa.Column('has_dormitory', sa.Boolean(), nullable=True))
    op.create_index('ix_university_has_dormitory', 'universities', ['has_dormitory'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_university_has_dormitory', table_name='universities')
    op.drop_column('universities', 'has_dormitory')
    op.add_column('dormitory', sa.Column('dormitory', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index('ix_dormitory_dormitory', 'dormitory', ['dormitory'], unique=False)
    # ### end Alembic commands ###
