"""MIGRATION=connect_uni_obsh_id

Revision ID: dc9d2b7bc296
Revises: 0dcfea9db417
Create Date: 2025-04-11 13:43:08.254977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc9d2b7bc296'
down_revision: Union[str, None] = '0dcfea9db417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dormitory', sa.Column('university_id', sa.Integer(), nullable=False))
    op.drop_constraint('dormitory_vuz_long_name_key', 'dormitory', type_='unique')
    op.create_unique_constraint(None, 'dormitory', ['university_id'])
    op.drop_constraint('dormitory_vuz_long_name_fkey', 'dormitory', type_='foreignkey')
    op.create_foreign_key(None, 'dormitory', 'universities', ['university_id'], ['id'])
    op.drop_column('dormitory', 'vuz_long_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dormitory', sa.Column('vuz_long_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dormitory', type_='foreignkey')
    op.create_foreign_key('dormitory_vuz_long_name_fkey', 'dormitory', 'universities', ['vuz_long_name'], ['long_name'])
    op.drop_constraint(None, 'dormitory', type_='unique')
    op.create_unique_constraint('dormitory_vuz_long_name_key', 'dormitory', ['vuz_long_name'])
    op.drop_column('dormitory', 'university_id')
    # ### end Alembic commands ###
